language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
addons:
  sauce_connect:
    username: "rzrsharp_oss"
    access_key:
      secure: "I1NDD3XOo0Swf4IrkXyyL7H1V+mX3pGN6XZvdvi6+xM8rHtBuokAdpUBH9gr51bbDtKTmBX7XR9AXmr/tBToxsULnDWOXmQV/PpNLCQT7gHFQIoGBqbQkaGt0G0JM6VxXp1urnJv7I0U5gN+yksT87lIIfcHCZA9Bhpw71tFYxk="
