language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
env:
  global:
  - SAUCE_USERNAME=rzrsharp_oss
  - secure: ZD6UqM7v7PVX6nLJZeM3VVLs21vVbLdGFdhdq9nq4hHcf+9/ag8/iGwqGc93CeorNhjeTKWcvQf7am0LcJeRWAfOTFHFYkODkF8EDxpNB/ppZWUeAMvGd+bg7iCCFtu+OR4aG5rX9n9NnyaiD00NnDwxswdwi3KqN0dmWW5aJEc=
